services:
    bb3mobi.TopicsArticles.listener:
        class: bb3mobi\TopicsArticles\event\listener
        arguments:
            - @template
            - @request
            - @user
            - @auth
        tags:
            - { name: event.listener }
